include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-vIwI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wtc-list-add-fn-d0255eea-37ce-4cfd-a68c-2ea25826b4de
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-vIwI
  environment:
    name: wtc-list-add-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-09T16:50:31Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wtc-list-add-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: wtc-list-add-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: wtc-list-add-fn-d0255eea-37ce-4cfd-a68c-2ea25826b4de
      namespace: default
  requestsPerPod: 10000
  resources: {}
