include:
- ./func/*
kind: ArchiveUploadSpec
name: func-VRaO

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: watch-list-save-fn-466770fa-9cfb-401a-81a0-3d1b4d409d79
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: watch-list-save-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-VRaO
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-31T18:53:49Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: watch-list-save-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 6
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: watch-list-save-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.save_symbols
    packageref:
      name: watch-list-save-fn-466770fa-9cfb-401a-81a0-3d1b4d409d79
      namespace: default
  requestsPerPod: 100000
  resources: {}
