apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: wtc-list-add-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: wtc-list-add-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /watch_list/variable_income/add
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /watch_list/variable_income/add
