include:
- ./func/*
kind: ArchiveUploadSpec
name: func-CLvI

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wathc-list-save-fn-683cfe15-f69d-4070-be7d-ca7094b3c765
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: wathc-list-save-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-CLvI
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-27T19:48:05Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wathc-list-save-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: wathc-list-save-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.save_symbols
    packageref:
      name: wathc-list-save-fn-683cfe15-f69d-4070-be7d-ca7094b3c765
      namespace: default
  requestsPerPod: 100000
  resources: {}
