include:
- ./func/*
kind: ArchiveUploadSpec
name: func-MiXh

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wathc-list-save-fn-4f5cf277-bcf0-4261-9d3c-d5d3dccae985
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: wathc-list-save-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-MiXh
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-27T18:05:24Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wathc-list-save-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: wathc-list-save-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.save_symbols
    packageref:
      name: wathc-list-save-fn-4f5cf277-bcf0-4261-9d3c-d5d3dccae985
      namespace: default
  requestsPerPod: 100000
  resources: {}
