apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 8a58ab3e-00f8-4936-87db-30db763012c5
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: wathc-list-save-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /watch_list/add
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /watch_list/add
