apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 5609e3fc-535d-45fa-85ff-6e5f1d829233
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: wathc-list-save-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /wathc_list/add
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /wathc_list/add
