apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: ee6783a2-5427-4504-a66d-5bc402f8ed9b
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: wathc-list-save-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /watch_list/add
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /watch_list/add
